server:
  port: 8081
spring:
  application:
    name: MetaboTrack-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${metabo.datasource.url}
    username: ${metabo.datasource.username}
    password: ${metabo.datasource.password}