package com.metabotrackapi.vo;

import com.metabotrackapi.enumeration.CalorieEfficiencyEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.util.List;

@Data
@Builder
@Schema(description = "The calculated projection result from the rule engine")
public class SimulationResultVO {

    @Schema(description = "The user's current average score before simulation", example = "7.2")
    private Double baselineScore;

    @Schema(description = "The new projected score if the hypothetical targets are met", example = "8.5")
    private Double projectedScore;

    @Schema(description = "String representation of the net change (e.g., '+1.3' or '-0.5')", example = "+1.3")
    private String scoreChange;

    @Schema(description = "The projected efficiency tier", example = "HIGH")
    private CalorieEfficiencyEnum projectedTier;

    @Schema(description = "Actionable, human-readable feedback generated by the rule engine", example = "['Excellent sleep bonus applied.', 'Warning: Low active minutes.']")
    private List<String> feedbackMessages;
}